### ISSUE TITLE
Support for mime-type application/octet-stream

### ISSUE THREAD

**Issue by andreaPorini** [OOlashyn/PCF-AttachmentGalleryControl#1]
Hi @OOlashyn,

I've tried your PCF and it works great! 

I have only one problem, I've built a Canvas App in PowerApps linked to our CRM and when i upload a photo taken directly from the App, the gallery control "ignore" that photo.

With XrmToolbox, I've seen that the mime-type of the annotation is "application/octet-stream" and it seems that the component you've built skips that format fetching the attachments.

Is it possible to add support to that mime-type?

Best regards,
Andrea

**Comment by OOlashyn** [comment]
Hi @andreaPorini,

Happy that you like my PCF component. To increase performance of my component I retrieve just attachments with mime-type image/ and pdf as well. Regarding application/octet-stream - it is default mime-type when browser doesn't know what file type is it (found [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types) ). Because system might store not just image files with this extension I will need find some way to verify that it is an image before showing. I will investigate this more deeply and if possible will include in one of the next releases.

Best Regards,
Oleksandr Olashyn
